#!/bin/bash
# Build a SYNTHETIC rootfs that should pass every offline check in
# verify-image.sh.
#
#   tests/make-fixture.sh <dest-dir>
#
# This is not an image. It is the smallest filesystem that satisfies the
# harness's declared contract, and it exists so that self-test.sh can mutate it
# and prove the harness goes red -- without a 2-3 hour pi-gen build, and on any
# Linux box.
#
# It is deliberately built from the SAME facts the stage writes, but by
# different code. A fixture generated by the stage itself would make the
# self-test a tautology.

set -euo pipefail

DEST="${1:?usage: make-fixture.sh <dest-dir>}"
rm -rf "${DEST}"
mkdir -p "${DEST}"

SU=default
# The fixture's service user IS the invoking uid, so ownership assertions hold
# without root. The harness reads the uid out of the fixture's own /etc/passwd,
# so this is not a special case in the harness -- only in the fixture.
SU_UID="$(id -u)"
SU_GID="$(id -g)"

mkdir -p "${DEST}"/{etc,usr/local/bin,usr/local/sbin,usr/share/elspi/drm-modes}
mkdir -p "${DEST}"/boot/firmware
mkdir -p "${DEST}"/etc/systemd/system
mkdir -p "${DEST}"/var/lib/dpkg
mkdir -p "${DEST}"/var/log
mkdir -p "${DEST}"/opt/reflex-venv/bin
mkdir -p "${DEST}"/opt/reflex-venv/lib/python3.13/site-packages/kivy-2.3.1.dist-info
mkdir -p "${DEST}"/opt/reflex-venv/lib/python3.13/site-packages/kivy/graphics
mkdir -p "${DEST}"/var/lib/reflex-config "${DEST}"/var/log/reflex "${DEST}"/home/default/projects

# --- identity ---------------------------------------------------------------
printf 'root:x:0:0:root:/root:/bin/bash\n%s:x:%s:%s::/home/%s:/bin/bash\n' \
	"${SU}" "${SU_UID}" "${SU_GID}" "${SU}" > "${DEST}/etc/passwd"

: > "${DEST}/etc/group"
for g in dialout video render input plugdev netdev spi i2c gpio audio sudo; do
	printf '%s:x:999:%s\n' "${g}" "${SU}" >> "${DEST}/etc/group"
done

printf 'root:*:20000:0:99999:7:::\n%s:!:20000:0:99999:7:::\n' "${SU}" \
	> "${DEST}/etc/shadow"

# --- manifest ---------------------------------------------------------------
cat > "${DEST}/etc/elspi-image.json" <<JSON
{
  "image": "elspi-fixture",
  "arch": "armhf",
  "release": "trixie",
  "service_user": "${SU}",
  "runs_as_root": false,
  "paths": {
    "venv": "/opt/reflex-venv",
    "app_parent": "/home/default/projects",
    "app_root": "/home/default/projects/reflex",
    "config_dir": "/var/lib/reflex-config",
    "log_dir": "/var/log/reflex"
  },
  "drm": {
    "default_mode": "first-opener",
    "modes": ["first-opener", "logind-seat", "cap-sys-admin"],
    "switcher": "/usr/local/sbin/elspi-drm-mode",
    "verified_on_hardware": false
  },
  "first_boot_seed": {
    "source": "raspberry-pi-imager-2.x-os-customisation",
    "unit": "/etc/systemd/system/elspi-first-boot-seed.service",
    "script": "/usr/local/sbin/elspi-first-boot-seed",
    "neutralises_after_use": [
      "/boot/firmware/user-data",
      "/boot/firmware/network-config"
    ],
    "leaves_intact": ["/boot/firmware/meta-data"],
    "verified_on_hardware": false
  },
  "reflex_lock_commit": "0000000000000000000000000000000000000000",
  "cannot_be_verified_without_hardware": [
    "DRM master acquisition (no GPU in the harness)",
    "the touchscreen",
    "SPI, I2C and the UART link to the STM32"
  ]
}
JSON

# --- dpkg status ------------------------------------------------------------
: > "${DEST}/var/lib/dpkg/status"
for p in libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libmtdev1t64 \
         libgbm1 libdrm2 libgl1-mesa-dri network-manager libsdl2-dev \
         libmtdev-dev python3-dev build-essential pkg-config \
         gcc-arm-none-eabi cmake openocd plymouth libx11-6; do
	printf 'Package: %s\nStatus: install ok installed\nVersion: 1\n\n' "${p}" \
		>> "${DEST}/var/lib/dpkg/status"
done

# --- venv -------------------------------------------------------------------
# The venv python is an ABSOLUTE SYMLINK, exactly as uv writes it.
#
# This used to be a plain executable file, which was convenient and WRONG, and
# the convenience cost a build: verify-image.sh tested it with `test -x`, that
# passed against the fixture, and then failed against a real image where the
# absolute target resolves against the host root instead of the rootfs. A
# fixture that is easier than reality launders the bug it should have caught.
mkdir -p "${DEST}/usr/bin"
printf '#!/bin/sh\necho fixture-python\n' > "${DEST}/usr/bin/python3.13"
chmod 0755 "${DEST}/usr/bin/python3.13"
ln -sf python3.13 "${DEST}/usr/bin/python3"
ln -sf /usr/bin/python3 "${DEST}/opt/reflex-venv/bin/python"
printf 'Name: kivy\nVersion: 2.3.1\n' \
	> "${DEST}/opt/reflex-venv/lib/python3.13/site-packages/kivy-2.3.1.dist-info/METADATA"
printf 'Tag: cp313-cp313-linux_armv7l\n' \
	> "${DEST}/opt/reflex-venv/lib/python3.13/site-packages/kivy-2.3.1.dist-info/WHEEL"
: > "${DEST}/opt/reflex-venv/lib/python3.13/site-packages/kivy/graphics/context_instructions.cpython-313-arm-linux-gnueabihf.so"

# --- an ARM ELF for `file` to recognise -------------------------------------
# 32-bit LSB ELF header with e_machine = 40 (EM_ARM). Enough for file(1); it is
# not runnable and does not need to be.
python3 - "${DEST}/usr/local/bin/uv" <<'PY'
import struct, sys
h  = b"\x7fELF" + bytes([1, 1, 1, 0]) + b"\x00" * 8
h += struct.pack("<HHI", 2, 40, 1)          # e_type=EXEC, e_machine=EM_ARM
h += struct.pack("<III", 0x8000, 52, 0)     # entry, phoff, shoff
h += struct.pack("<IHHHHHH", 0, 52, 32, 1, 40, 0, 0)
open(sys.argv[1], "wb").write(h + b"\x00" * 64)
PY
chmod 0755 "${DEST}/usr/local/bin/uv"

# --- boot configuration -----------------------------------------------------
cat > "${DEST}/boot/firmware/config.txt" <<'CFG'
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
camera_auto_detect=0
display_auto_detect=1
auto_initramfs=1
dtoverlay=vc4-kms-v3d
max_framebuffers=2
disable_overscan=1
arm_boost=1

[pi5]
dtoverlay=nospi10

[all]
enable_uart=1
disable_splash=1
usb_max_current_enable=1
CFG

printf 'console=tty1 root=ROOTDEV rootfstype=ext4 fsck.repair=yes rootwait quiet splash logo.nologo plymouth.ignore-serial-consoles\n' \
	> "${DEST}/boot/firmware/cmdline.txt"

# --- serial getty mask ------------------------------------------------------
ln -sf /dev/null "${DEST}/etc/systemd/system/serial-getty@ttyAMA0.service"

# --- audio ------------------------------------------------------------------
printf 'defaults.pcm.card 0\ndefaults.ctl.card 0\n' > "${DEST}/etc/asound.conf"

# --- timezone ---------------------------------------------------------------
mkdir -p "${DEST}/usr/share/zoneinfo/America"
: > "${DEST}/usr/share/zoneinfo/America/New_York"
ln -sf ../usr/share/zoneinfo/America/New_York "${DEST}/etc/localtime"

# --- drm plumbing -----------------------------------------------------------
printf '[Service]\nUser=%s\nGroup=%s\n\n[Unit]\nAfter=plymouth-quit-wait.service\n' \
	"${SU}" "${SU}" > "${DEST}/usr/share/elspi/drm-modes/first-opener.conf"
printf '[Service]\nUser=%s\nGroup=%s\n' "${SU}" "${SU}" \
	> "${DEST}/usr/share/elspi/drm-modes/logind-seat.conf"
printf '[Service]\nUser=%s\nGroup=%s\nAmbientCapabilities=CAP_SYS_ADMIN\n' "${SU}" "${SU}" \
	> "${DEST}/usr/share/elspi/drm-modes/cap-sys-admin.conf"
printf '[Service]\nExecStart=\nExecStart=-/sbin/agetty --autologin %s --noclear %%I $TERM\n' "${SU}" \
	> "${DEST}/usr/share/elspi/getty-tty1-autologin.conf"

printf '#!/bin/bash\n# fixture stub: first-opener logind-seat cap-sys-admin\n' \
	> "${DEST}/usr/local/sbin/elspi-drm-mode"
chmod 0755 "${DEST}/usr/local/sbin/elspi-drm-mode"

# --- the first-boot seed (stage-elspi/12-first-boot-seed) -------------------
# The cloud-init seed files as they leave the BUILD: meta-data carrying a
# HYPHENATED instance-id, because upstream's underscored `instance_id` is read
# by nobody -- cloud-init 25.2's NoCloud datasource wants `instance-id` and
# otherwise falls back to the literal "nocloud".
#
# Written here by hand rather than by copying what the stage emits: a fixture
# generated by the code under test proves only that the author can copy a path.
cat > "${DEST}/boot/firmware/meta-data" <<'META'
dsmode: local
instance-id: elspi-fixture
META
printf '#cloud-config\n' > "${DEST}/boot/firmware/user-data"
printf 'network: {version: 2}\n' > "${DEST}/boot/firmware/network-config"

printf '#!/bin/bash\n# fixture stub: elspi first-boot seed\nexit 0\n' \
	> "${DEST}/usr/local/sbin/elspi-first-boot-seed"
chmod 0755 "${DEST}/usr/local/sbin/elspi-first-boot-seed"

# The ExecStart '-' prefix is part of the contract, not cosmetic: elspi has no
# terminal, so the seed script must not be able to fail the boot.
cat > "${DEST}/etc/systemd/system/elspi-first-boot-seed.service" <<'UNIT'
[Unit]
Description=elspi first-boot seed (radio, regulatory domain, seed neutralisation)
After=cloud-final.service
After=NetworkManager.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=-/usr/local/sbin/elspi-first-boot-seed

[Install]
WantedBy=multi-user.target
UNIT

# Enabled exactly the way `systemctl enable` would do it: a RELATIVE symlink in
# multi-user.target.wants. Relative matters -- an absolute one would resolve
# against the host root when the harness follows it from outside.
mkdir -p "${DEST}/etc/systemd/system/multi-user.target.wants"
ln -sf ../elspi-first-boot-seed.service \
	"${DEST}/etc/systemd/system/multi-user.target.wants/elspi-first-boot-seed.service"

echo "fixture built at ${DEST}"
