#!/bin/bash
# Build a SYNTHETIC rootfs that should pass every offline check in
# verify-image.sh.
#
#   tests/make-fixture.sh <dest-dir>
#
# This is not an image. It is the smallest filesystem that satisfies the
# harness's declared contract, and it exists so that self-test.sh can mutate it
# and prove the harness goes red -- without a 2-3 hour pi-gen build, and on any
# Linux box.
#
# It is deliberately built from the SAME facts the stage writes, but by
# different code. A fixture generated by the stage itself would make the
# self-test a tautology.

set -euo pipefail

DEST="${1:?usage: make-fixture.sh <dest-dir>}"
rm -rf "${DEST}"
mkdir -p "${DEST}"

SU=default
# The fixture's service user IS the invoking uid, so ownership assertions hold
# without root. The harness reads the uid out of the fixture's own /etc/passwd,
# so this is not a special case in the harness -- only in the fixture.
SU_UID="$(id -u)"
SU_GID="$(id -g)"

mkdir -p "${DEST}"/{etc,usr/local/bin,usr/local/sbin,usr/share/elspi/drm-modes}
mkdir -p "${DEST}"/boot/firmware
mkdir -p "${DEST}"/etc/systemd/system
mkdir -p "${DEST}"/var/lib/dpkg
mkdir -p "${DEST}"/var/log
mkdir -p "${DEST}"/opt/reflex-venv/bin
mkdir -p "${DEST}"/opt/reflex-venv/lib/python3.13/site-packages/kivy-2.3.1.dist-info
mkdir -p "${DEST}"/opt/reflex-venv/lib/python3.13/site-packages/kivy/graphics
mkdir -p "${DEST}"/var/lib/reflex-config "${DEST}"/var/log/reflex "${DEST}"/home/default/projects

# --- identity ---------------------------------------------------------------
printf 'root:x:0:0:root:/root:/bin/bash\n%s:x:%s:%s::/home/%s:/bin/bash\n' \
	"${SU}" "${SU_UID}" "${SU_GID}" "${SU}" > "${DEST}/etc/passwd"

: > "${DEST}/etc/group"
for g in dialout video render input plugdev netdev spi i2c gpio audio sudo; do
	printf '%s:x:999:%s\n' "${g}" "${SU}" >> "${DEST}/etc/group"
done

printf 'root:*:20000:0:99999:7:::\n%s:!:20000:0:99999:7:::\n' "${SU}" \
	> "${DEST}/etc/shadow"

# --- manifest ---------------------------------------------------------------
cat > "${DEST}/etc/elspi-image.json" <<JSON
{
  "image": "elspi-fixture",
  "arch": "armhf",
  "release": "trixie",
  "built_utc": "2026-01-01T00:00:00Z",
  "service_user": "${SU}",
  "runs_as_root": false,
  "paths": {
    "venv": "/opt/reflex-venv",
    "app_parent": "/home/default/projects",
    "app_root": "/home/default/projects/reflex",
    "config_dir": "/var/lib/reflex-config",
    "log_dir": "/var/log/reflex"
  },
  "drm": {
    "default_mode": "first-opener",
    "modes": ["first-opener", "cap-sys-admin"],
    "switcher": "/usr/local/sbin/elspi-drm-mode",
    "verified_on_hardware": true
  },
  "first_boot_seed": {
    "source": "raspberry-pi-imager-2.x-os-customisation",
    "unit": "/etc/systemd/system/elspi-first-boot-seed.service",
    "script": "/usr/local/sbin/elspi-first-boot-seed",
    "neutralises_after_use": [
      "/boot/firmware/user-data",
      "/boot/firmware/network-config"
    ],
    "leaves_intact": ["/boot/firmware/meta-data"],
    "verified_on_hardware": true
  },
  "ssh": {
    "enabled": true,
    "key_source": "imager-seed",
    "keys_installed_by": "/usr/local/sbin/elspi-first-boot-seed",
    "baked_authorized_keys": false,
    "auth": "imager-choice",
    "image_sets_auth_options": false
  },
  "build_defaults": {
    "hostname": "elspi",
    "timezone": "Etc/UTC",
    "locale": "en_US.UTF-8",
    "keymap": "us",
    "replaced_per_card_by_imager": ["hostname", "timezone", "keymap"]
  },
  "first_boot_ui": {
    "unit": "/etc/systemd/system/elspi-first-boot-ui.service",
    "script": "/usr/local/sbin/elspi-first-boot-ui",
    "status": "scaffold only, see stage-elspi/14-first-boot-ui/README.md",
    "verified_on_hardware": false
  },
  "baked_app": {
    "release": "v1.0.0",
    "commit": "@@APP_COMMIT@@",
    "root": "/home/default/projects/reflex",
    "source_form": "git-checkout-with-tag-history",
    "selected_by": "stage-elspi/10a-app-checkout/files/select-release.sh",
    "updater_ready": true,
    "protocol_version_readable": true,
    "started_on_first_boot": false
  },
  "reflex_lock_commit": "0000000000000000000000000000000000000000",
  "image_build_sha": "fixture0000000000000000000000000000000000",
  "image_release": 1,
  "runtime_versions": {
    "python": "Python 3.13.0",
    "kivy": "2.3.1",
    "uv": "uv 0.4.18"
  },
  "cannot_be_verified_without_hardware": [
    "DRM master acquisition (no GPU in the harness)",
    "the touchscreen",
    "SPI, I2C and the UART link to the STM32",
    "the first-boot-ui hook's converge/start branch (stage-elspi/14-first-boot-ui): the branch is unwritten, so starting the baked app unattended has never executed end-to-end"
  ]
}
JSON

# --- dpkg status ------------------------------------------------------------
: > "${DEST}/var/lib/dpkg/status"
for p in libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libmtdev1t64 \
         libgbm1 libdrm2 libgl1-mesa-dri network-manager libsdl2-dev \
         libmtdev-dev python3-dev build-essential pkg-config \
         gcc-arm-none-eabi cmake openocd plymouth libx11-6 git; do
	printf 'Package: %s\nStatus: install ok installed\nVersion: 1\n\n' "${p}" \
		>> "${DEST}/var/lib/dpkg/status"
done

# --- venv -------------------------------------------------------------------
# The venv python is an ABSOLUTE SYMLINK, exactly as uv writes it.
#
# This used to be a plain executable file, which was convenient and WRONG, and
# the convenience cost a build: verify-image.sh tested it with `test -x`, that
# passed against the fixture, and then failed against a real image where the
# absolute target resolves against the host root instead of the rootfs. A
# fixture that is easier than reality launders the bug it should have caught.
mkdir -p "${DEST}/usr/bin"
printf '#!/bin/sh\necho fixture-python\n' > "${DEST}/usr/bin/python3.13"
chmod 0755 "${DEST}/usr/bin/python3.13"
ln -sf python3.13 "${DEST}/usr/bin/python3"
ln -sf /usr/bin/python3 "${DEST}/opt/reflex-venv/bin/python"
printf 'Name: kivy\nVersion: 2.3.1\n' \
	> "${DEST}/opt/reflex-venv/lib/python3.13/site-packages/kivy-2.3.1.dist-info/METADATA"
printf 'Tag: cp313-cp313-linux_armv7l\n' \
	> "${DEST}/opt/reflex-venv/lib/python3.13/site-packages/kivy-2.3.1.dist-info/WHEEL"
: > "${DEST}/opt/reflex-venv/lib/python3.13/site-packages/kivy/graphics/context_instructions.cpython-313-arm-linux-gnueabihf.so"

# --- an ARM ELF for `file` to recognise -------------------------------------
# 32-bit LSB ELF header with e_machine = 40 (EM_ARM). Enough for file(1); it is
# not runnable and does not need to be.
python3 - "${DEST}/usr/local/bin/uv" <<'PY'
import struct, sys
h  = b"\x7fELF" + bytes([1, 1, 1, 0]) + b"\x00" * 8
h += struct.pack("<HHI", 2, 40, 1)          # e_type=EXEC, e_machine=EM_ARM
h += struct.pack("<III", 0x8000, 52, 0)     # entry, phoff, shoff
h += struct.pack("<IHHHHHH", 0, 52, 32, 1, 40, 0, 0)
open(sys.argv[1], "wb").write(h + b"\x00" * 64)
PY
chmod 0755 "${DEST}/usr/local/bin/uv"

# --- the commands the runtime shells out to ---------------------------------
# The image's own /usr/bin/git was the gap the first real card hit
# (2026-09-13); the rest are the set the UI, the in-app updater and the three
# delta phases invoke by name.
#
# visudo goes in /usr/sbin DELIBERATELY, which is where Debian puts it. Laying
# every stub in /usr/bin would make the fixture easier than reality and would
# quietly stop exercising the harness's PATH search -- the same mistake the
# venv python symlink note above records.
mkdir -p "${DEST}/usr/sbin"
for b in git systemctl sudo nmcli sed grep awk getent stat find mktemp tar \
         ssh-keygen passwd openocd install; do
	printf '#!/bin/sh\necho fixture-%s\n' "${b}" > "${DEST}/usr/bin/${b}"
	chmod 0755 "${DEST}/usr/bin/${b}"
done
printf '#!/bin/sh\necho fixture-visudo\n' > "${DEST}/usr/sbin/visudo"
chmod 0755 "${DEST}/usr/sbin/visudo"

# --- the polkit rule (stage-elspi/05-service-user) --------------------------
# The OTHER half of the non-root decision, and the one that was missing from
# image addcb2e: the service user has no logind session, so polkit gives it
# NetworkManager's "any" default -- "no" for enable-disable-wifi -- and the
# UI's Network screen dies on `nmcli radio wifi on`.
#
# Written out here by hand rather than copied from the stage's files/ dir, for
# the reason stated at the top of this file: a fixture generated by the code
# under test only proves the author can copy a path. NOTE that the only
# occurrence of the service user's name is the subject.user line, which is
# what self-test.sh's substitution mutation depends on.
mkdir -p "${DEST}/etc/polkit-1/rules.d"
cat > "${DEST}/etc/polkit-1/rules.d/50-reflex-service-user.rules" <<RULE
// fixture stub: NetworkManager for the sessionless service user
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.NetworkManager.") === 0 &&
        subject.user === "${SU}") {
        return polkit.Result.YES;
    }
});
RULE
chmod 0644 "${DEST}/etc/polkit-1/rules.d/50-reflex-service-user.rules"

# --- boot configuration -----------------------------------------------------
cat > "${DEST}/boot/firmware/config.txt" <<'CFG'
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
camera_auto_detect=0
display_auto_detect=1
auto_initramfs=1
dtoverlay=vc4-kms-v3d
max_framebuffers=2
disable_overscan=1
arm_boost=1

[pi5]
dtoverlay=nospi10

[all]
enable_uart=1
disable_splash=1
usb_max_current_enable=1
CFG

printf 'console=tty1 root=ROOTDEV rootfstype=ext4 fsck.repair=yes rootwait quiet splash logo.nologo plymouth.ignore-serial-consoles\n' \
	> "${DEST}/boot/firmware/cmdline.txt"

# --- serial getty mask ------------------------------------------------------
ln -sf /dev/null "${DEST}/etc/systemd/system/serial-getty@ttyAMA0.service"

# --- audio ------------------------------------------------------------------
printf 'defaults.pcm.card 0\ndefaults.ctl.card 0\n' > "${DEST}/etc/asound.conf"

# --- timezone ---------------------------------------------------------------
mkdir -p "${DEST}/usr/share/zoneinfo/Etc"
: > "${DEST}/usr/share/zoneinfo/Etc/UTC"
ln -sf ../usr/share/zoneinfo/Etc/UTC "${DEST}/etc/localtime"

# --- drm plumbing -----------------------------------------------------------
# TWO fragments, not three. `logind-seat` -- and the tty1 autologin fragment
# that only that mode installed -- were deleted 2026-09-13 once first-opener
# was verified on hardware, so the fixture must NOT stage them: verify-image.sh
# asserts they are absent, and a fixture that still carried them would make
# that assertion unfalsifiable in the other direction.
printf '[Service]\nUser=%s\nGroup=%s\n\n[Unit]\nAfter=plymouth-quit-wait.service\n' \
	"${SU}" "${SU}" > "${DEST}/usr/share/elspi/drm-modes/first-opener.conf"
printf '[Service]\nUser=%s\nGroup=%s\nAmbientCapabilities=CAP_SYS_ADMIN\n' "${SU}" "${SU}" \
	> "${DEST}/usr/share/elspi/drm-modes/cap-sys-admin.conf"

# The switcher stub carries its mode list the way the real one does -- a
# VALID_MODES line -- because that is the form verify-image.sh asserts on, and
# self-test.sh mutates this line to prove the assertion can go red.
printf '#!/bin/bash\n# fixture stub\nVALID_MODES="first-opener cap-sys-admin"\n' \
	> "${DEST}/usr/local/sbin/elspi-drm-mode"
chmod 0755 "${DEST}/usr/local/sbin/elspi-drm-mode"

# --- the first-boot seed (stage-elspi/12-first-boot-seed) -------------------
# The cloud-init seed files as they leave the BUILD: meta-data carrying a
# HYPHENATED instance-id, because upstream's underscored `instance_id` is read
# by nobody -- cloud-init 25.2's NoCloud datasource wants `instance-id` and
# otherwise falls back to the literal "nocloud".
#
# Written here by hand rather than by copying what the stage emits: a fixture
# generated by the code under test proves only that the author can copy a path.
cat > "${DEST}/boot/firmware/meta-data" <<'META'
dsmode: local
instance-id: elspi-fixture
META
printf '#cloud-config\n' > "${DEST}/boot/firmware/user-data"
printf 'network: {version: 2}\n' > "${DEST}/boot/firmware/network-config"

printf '#!/bin/bash\n# fixture stub: elspi first-boot seed\nexit 0\n' \
	> "${DEST}/usr/local/sbin/elspi-first-boot-seed"
chmod 0755 "${DEST}/usr/local/sbin/elspi-first-boot-seed"

# The ExecStart '-' prefix is part of the contract, not cosmetic: elspi has no
# terminal, so the seed script must not be able to fail the boot.
cat > "${DEST}/etc/systemd/system/elspi-first-boot-seed.service" <<'UNIT'
[Unit]
Description=elspi first-boot seed (radio, regulatory domain, seed neutralisation)
After=cloud-final.service
After=NetworkManager.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=-/usr/local/sbin/elspi-first-boot-seed
ProtectHome=no

[Install]
WantedBy=cloud-init.target
UNIT

# Enabled exactly the way `systemctl enable` would do it: a RELATIVE symlink in
# cloud-init.target.wants. Relative matters -- an absolute one would resolve
# against the host root when the harness follows it from outside.
#
# cloud-init.target and NOT multi-user.target: this unit is After=cloud-final
# and cloud-final is After=multi-user.target, so enabling it in
# multi-user.target.wants is an ordering cycle. The fixture models the FIXED
# image; tests/self-test.sh mutates it back to the broken shape.
mkdir -p "${DEST}/etc/systemd/system/cloud-init.target.wants"
ln -sf ../elspi-first-boot-seed.service \
	"${DEST}/etc/systemd/system/cloud-init.target.wants/elspi-first-boot-seed.service"

# --- SSH: keyless, and no authentication policy of the image's own ----------
# DECIDED 2026-09-23. No authorized_keys anywhere (keys arrive from the Imager
# seed at flash time), and sshd_config in Debian's stock SHAPE: the drop-in
# Include at the top, the authentication options present only as comments,
# and an EMPTY sshd_config.d. That is what makes Imager's per-card choice --
# cloud-init's 50-cloud-init.conf -- the one sshd reads first.
#
# Written by hand, like the rest of this fixture. The seed unit's
# ProtectHome=no (above) is part of the same contract: the script writes the
# seeded keys into /home.
mkdir -p "${DEST}/etc/ssh/sshd_config.d"
cat > "${DEST}/etc/ssh/sshd_config" <<'SSHD'
# fixture: Debian trixie's stock sshd_config, abridged
Include /etc/ssh/sshd_config.d/*.conf
#PubkeyAuthentication yes
#PasswordAuthentication yes
#PermitEmptyPasswords no
KbdInteractiveAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_* COLORTERM NO_COLOR
Subsystem	sftp	/usr/lib/openssh/sftp-server
SSHD

# --- the first-boot UI hook (stage-elspi/14-first-boot-ui) ------------------
# A scaffold, not a feature -- see stage-elspi/14-first-boot-ui/README.md.
# The fixture's stub just exits 0, same as the seed's stub above: the real
# script only ever logs a verdict (UNIMPLEMENTED on every image that bakes the
# app in) and exits 0.
printf '#!/bin/bash\n# fixture stub: elspi first-boot ui (logs a verdict, starts nothing)\nexit 0\n' \
	> "${DEST}/usr/local/sbin/elspi-first-boot-ui"
chmod 0755 "${DEST}/usr/local/sbin/elspi-first-boot-ui"

cat > "${DEST}/etc/systemd/system/elspi-first-boot-ui.service" <<'UNIT'
[Unit]
Description=elspi first-boot UI hook (would converge+start the baked reflex-ui; that branch is unwritten, so it only logs a verdict)
After=elspi-first-boot-seed.service
After=plymouth-quit-wait.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=-/usr/local/sbin/elspi-first-boot-ui

[Install]
WantedBy=cloud-init.target
UNIT

# Same anchor as the seed, same reason: cloud-init.target.wants, never
# multi-user.target.wants (this unit is After=elspi-first-boot-seed.service,
# which is After=cloud-final.service -- multi-user.target.wants would be the
# 2026-09-13 ordering cycle again).
ln -sf ../elspi-first-boot-ui.service \
	"${DEST}/etc/systemd/system/cloud-init.target.wants/elspi-first-boot-ui.service"

# --- USB automount (stage-elspi/13-usb-automount, order 2026-09-16#6) ------
# Written by hand, for the reason stated at the top of this file: mirrors
# the SHAPE the real stage installs (a udev rule naming the service user's
# uid/gid and carrying noexec among the systemd-mount options, plus an
# executable sanitizer helper) rather than depending on the real rule's
# exact wording, so self-test.sh's mutations below have a real contract to
# break rather than a copy of the file under test.
#
# @@SU_UID@@/@@SU_GID@@ substituted the same way the real stage substitutes
# @@SERVICE_UID@@/@@SERVICE_GID@@ -- a quoted heredoc first, so none of the
# udev rule's own $-syntax ($env{...}, $kernel, $devnode) is touched by THIS
# script's shell, then a targeted sed for just the two placeholders.
mkdir -p "${DEST}/etc/udev/rules.d"
cat > "${DEST}/etc/udev/rules.d/90-elspi-usb-automount.rules" <<'RULE'
ACTION=="add", SUBSYSTEM=="block", ENV{ID_BUS}=="usb", ENV{ID_FS_USAGE}=="filesystem", ENV{ID_FS_TYPE}=="vfat|exfat|ntfs", \
	PROGRAM="/usr/local/lib/elspi/elspi-usb-mount-name '$env{ID_FS_LABEL}' '$kernel'", \
	ENV{ELSPI_MOUNT_NAME}="%c", \
	RUN+="/usr/bin/systemd-mount --no-block --automount=yes --bind-device --collect -o uid=@@SU_UID@@,gid=@@SU_GID@@,umask=022,nosuid,nodev,noexec $devnode /media/$env{ELSPI_MOUNT_NAME}"
RULE
sed -i -e "s/@@SU_UID@@/${SU_UID}/g" -e "s/@@SU_GID@@/${SU_GID}/g" \
	"${DEST}/etc/udev/rules.d/90-elspi-usb-automount.rules"
chmod 0644 "${DEST}/etc/udev/rules.d/90-elspi-usb-automount.rules"

mkdir -p "${DEST}/usr/local/lib/elspi"
printf '#!/bin/bash\n# fixture stub: elspi-usb-mount-name\nprintf "%%s\\n" "${1:-fallback}"\n' \
	> "${DEST}/usr/local/lib/elspi/elspi-usb-mount-name"
chmod 0755 "${DEST}/usr/local/lib/elspi/elspi-usb-mount-name"

# --- the baked application checkout (stage-elspi/10a-app-checkout) ---------
# docs/design/seam.md amendment 2026-09-21: the image ships the app as a REAL
# GIT CHECKOUT at a full release tag, carrying tag history, owned by the
# service user.
#
# A REAL REPOSITORY, not a directory with a `.git` file in it. The properties
# the harness has to be able to check -- "the tag resolves", "git show
# <tag>:<path> works", "there is more than one tag" -- are all properties of
# an object store, and a stub would let every one of them pass while a `git
# archive` export (the thing this stage exists to NOT ship) failed them all.
# Built with two tags and HEAD detached at the newer one, which is the shape
# the real stage leaves behind.
#
# Owned by the service user by construction: the fixture's service user IS the
# invoking uid (see the top of this file), so no chown and no root.
#
# IDENTITY IS SET LOCALLY, IN THIS THROWAWAY REPO ONLY. `git commit` refuses
# without user.email, and CI runners routinely have no global identity -- but
# `git -c user.email=...` on a command is how a real commit ends up signed as
# somebody it is not, so this is a `git -C <fixture> config` against a
# repository that is deleted at the end of the test and never pushed anywhere.
APP_ROOT_FIX="${DEST}/home/default/projects/reflex"
mkdir -p "${APP_ROOT_FIX}/ui/reflex/utils" "${APP_ROOT_FIX}/fw/scripts"

cat > "${APP_ROOT_FIX}/ui/pyproject.toml" <<'TOML'
[project]
name = "reflex"
version = "1.0.0"
TOML

# The file ui/reflex/utils/updater.py reads the TARGET release's protocol
# version out of, with `git show <tag>:ui/reflex/utils/els_stop_map.py`. Its
# presence AT A TAG is what makes that read answerable.
cat > "${APP_ROOT_FIX}/ui/reflex/utils/els_stop_map.py" <<'PY'
# fixture stub: emitted by tools/genregs.py in the real repo
PROTOCOL_VERSION = 9
PY

# resolve_checkout() refuses a tree missing either of these -- "a directory
# with no fw/" -- so the fixture carries them and self-test.sh can take them
# away again.
printf '# fixture stub\n' > "${APP_ROOT_FIX}/fw/scripts/modbus-flash.py"
printf '# fixture stub\n' > "${APP_ROOT_FIX}/fw/scripts/reflex_image.py"

git -C "${APP_ROOT_FIX}" init -q
git -C "${APP_ROOT_FIX}" config user.email "fixture@example.invalid"
git -C "${APP_ROOT_FIX}" config user.name  "elspi fixture"
git -C "${APP_ROOT_FIX}" config commit.gpgsign false
git -C "${APP_ROOT_FIX}" add -A
git -C "${APP_ROOT_FIX}" commit -q -m "fixture: v0.9.0"
git -C "${APP_ROOT_FIX}" tag v0.9.0
printf 'PROTOCOL_VERSION = 9\n' >> "${APP_ROOT_FIX}/ui/reflex/utils/els_stop_map.py"
git -C "${APP_ROOT_FIX}" add -A
git -C "${APP_ROOT_FIX}" commit -q -m "fixture: v1.0.0"
git -C "${APP_ROOT_FIX}" tag v1.0.0
# Detached AT THE TAG, which is where both this stage and the in-app updater
# leave HEAD. A fixture sitting on a branch would let a harness that checks
# "HEAD == the declared tag" pass for the wrong reason.
git -C "${APP_ROOT_FIX}" checkout -q --detach v1.0.0
# The remote the real image ships: anonymous, public, and NOT the path the
# build read from.
git -C "${APP_ROOT_FIX}" remote add origin "https://github.com/Funkenjaeger/reflex.git"

APP_COMMIT_FIX="$(git -C "${APP_ROOT_FIX}" rev-parse --verify HEAD)"
sed -i "s/@@APP_COMMIT@@/${APP_COMMIT_FIX}/" "${DEST}/etc/elspi-image.json"

# The build-time fact files 10a-app-checkout writes and 11-manifest reads.
# They ship, so the harness can cross-check the manifest against them -- two
# files written from one measurement, which is only worth checking because
# they COULD disagree.
mkdir -p "${DEST}/etc/elspi"
printf '%s\n' "v1.0.0"              > "${DEST}/etc/elspi/reflex-app-release"
printf '%s\n' "${APP_COMMIT_FIX}"   > "${DEST}/etc/elspi/reflex-app-commit"
printf '%s\n' "yes"                 > "${DEST}/etc/elspi/reflex-app-updater-ready"
printf '%s\n' "yes"                 > "${DEST}/etc/elspi/reflex-app-protocol-readable"

# --- /etc/elspi-release -------------------------------------------------
# Generated FROM the manifest above by the same script the real build runs
# (stage-elspi/11-manifest/files/render-release.sh), not hand-written here --
# a fixture that reimplements the mapping would only prove the author copied
# it twice the same way. This is the one exception to this file's "written by
# hand, not by the code under test" rule stated at the top, and it is
# deliberate for the reason stage-elspi/11-manifest/files/render-release.sh's
# own header gives: the mapping from JSON keys to flat KEY=VALUE names lives
# in exactly one place.
HERE="$(cd "$(dirname "$0")" && pwd)"
bash "${HERE}/../stage-elspi/11-manifest/files/render-release.sh" generate "${DEST}" >/dev/null

echo "fixture built at ${DEST}"
