#!/bin/bash
# The switcher's ARGUMENT CONTRACT, executed rather than grepped.
#
#   tests/test-drm-mode-switcher.sh
#
# WHY THIS IS SEPARATE FROM verify-image.sh: that harness reads a synthetic
# rootfs whose elspi-drm-mode is a hand-written STUB (on purpose -- a fixture
# generated by the code under test only proves its author can copy a path), so
# it can assert what the real script SAYS but never what it DOES. This one runs
# the real /usr/local/sbin/elspi-drm-mode straight out of
# stage-elspi/06-seat/files and checks its exit status and its message.
#
# ONLY THE REFUSAL PATHS ARE EXECUTED, and that is deliberate. The accept path
# writes a systemd drop-in, reloads the daemon and enables a unit; running it
# on a dev box would be detonating the test instead of probing it. Every
# refusal returns before the script touches the filesystem, so this is
# payload-free by construction. Acceptance is asserted textually below, which
# is the most an off-Pi test can honestly claim.
#
# The rung this exists for: `logind-seat` was deleted 2026-09-13 after
# first-opener took the display on the real Pi at the first attempt. The
# switcher must now REFUSE that name with a message that names the two
# surviving modes -- an old note, an old field sheet or the printed flash
# ladder is the likeliest reason anyone types it, and "unknown mode" would
# leave them guessing on a machine with no terminal.

set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SWITCHER="${REPO}/stage-elspi/06-seat/files/elspi-drm-mode"

PASS=0
FAIL=0

ok()  { echo "  ok    $*"; PASS=$((PASS+1)); }
bad() { echo "  FAIL  $*"; FAIL=$((FAIL+1)); }

if [ ! -f "${SWITCHER}" ]; then
	echo "UNKNOWN: ${SWITCHER} not found -- nothing was checked. NOT a pass."
	exit 2
fi

# --- syntax -----------------------------------------------------------------
if bash -n "${SWITCHER}" 2>/dev/null; then
	ok "the switcher parses"
else
	bad "the switcher parses"
	echo "  (refusing to run a script that does not parse)"
	exit 1
fi

# --- the refusal paths, actually run ----------------------------------------
run_refusal() { # run_refusal <arg>
	OUT="$(bash "${SWITCHER}" "$1" 2>&1)"
	RC=$?
}

run_refusal logind-seat
if [ "${RC}" -ne 0 ]; then
	ok "logind-seat is refused (exit ${RC})"
else
	bad "logind-seat is refused -- it exited 0, so the deleted rung is still live"
fi
case "${OUT}" in
	*logind-seat*) ok "the refusal names the mode that was asked for" ;;
	*)             bad "the refusal names the mode that was asked for -- got: ${OUT}" ;;
esac
case "${OUT}" in
	*DELETED*) ok "the refusal says the mode was DELETED, not that it is unknown" ;;
	*)         bad "the refusal says the mode was DELETED -- got: ${OUT}" ;;
esac
for m in first-opener cap-sys-admin; do
	case "${OUT}" in
		*"${m}"*) ok "the refusal names the surviving mode ${m}" ;;
		*)        bad "the refusal names the surviving mode ${m} -- got: ${OUT}" ;;
	esac
done
# The refusal must not have touched anything. It runs as a normal user here,
# so a write would fail loudly rather than succeed, but the point is that the
# script returns BEFORE the root check, not that the root check saved it.
case "${OUT}" in
	*"must run as root"*) bad "the refusal returns before the root check" ;;
	*)                    ok  "the refusal returns before the root check" ;;
esac

run_refusal not-a-mode
if [ "${RC}" -ne 0 ]; then
	ok "an unknown mode is refused (exit ${RC})"
else
	bad "an unknown mode is refused -- it exited 0"
fi
for m in first-opener cap-sys-admin; do
	case "${OUT}" in
		*"${m}"*) ok "the unknown-mode message names ${m}" ;;
		*)        bad "the unknown-mode message names ${m} -- got: ${OUT}" ;;
	esac
done
case "${OUT}" in
	*logind-seat*) bad "the unknown-mode message does not advertise logind-seat" ;;
	*)             ok  "the unknown-mode message does not advertise logind-seat" ;;
esac

# Two arguments is a usage error, not a silently-ignored second mode.
OUT="$(bash "${SWITCHER}" first-opener cap-sys-admin 2>&1)"; RC=$?
if [ "${RC}" -ne 0 ]; then
	ok "two modes at once is a usage error (exit ${RC})"
else
	bad "two modes at once is a usage error -- it exited 0"
fi

# --- acceptance, asserted textually ----------------------------------------
# The one line the whole contract hangs on, in the CODE form the script uses.
if grep -q '^VALID_MODES="first-opener cap-sys-admin"$' "${SWITCHER}"; then
	ok "VALID_MODES is exactly: first-opener cap-sys-admin"
else
	bad "VALID_MODES is exactly 'first-opener cap-sys-admin' -- found: $(grep -m1 '^VALID_MODES=' "${SWITCHER}" 2>/dev/null || echo '<no VALID_MODES line>')"
fi
if grep -q '^RETIRED_MODES="logind-seat"$' "${SWITCHER}"; then
	ok "RETIRED_MODES still carries logind-seat, so the name is refused by hand"
else
	bad "RETIRED_MODES is exactly 'logind-seat' -- found: $(grep -m1 '^RETIRED_MODES=' "${SWITCHER}" 2>/dev/null || echo '<no RETIRED_MODES line>')"
fi

# The seat machinery itself must be gone from the script, not merely unreached.
for dead in 'systemctl --global enable' 'graphical-session.target' 'agetty'; do
	if grep -q -- "${dead}" "${SWITCHER}"; then
		bad "the seat machinery is gone: '${dead}' is still in the switcher"
	else
		ok "the seat machinery is gone: no '${dead}'"
	fi
done

# --- what this cannot answer ------------------------------------------------
echo
echo "  UNKNOWN  whether either surviving mode actually takes DRM master. That"
echo "           needs a GPU. first-opener was settled on the real Pi"
echo "           2026-09-13; nothing off the Pi can re-confirm it."

echo
echo "== result: ${PASS} ok, ${FAIL} failed =="
[ "${FAIL}" -eq 0 ]
